### ISSUE TITLE
Fails with certain javascript

### ISSUE THREAD

**Issue by purcell** [jlr/rainbow-delimiters#4]
`rainbow-delimiters` reports an unmatched delimiter on lines 25, 26, 57, 58, 59 and 60 of the javascript at https://gist.github.com/1477475. The code executes fine, and passes jslint, so I don't think I've made a stupid mistake.

This happens in both js-mode and js2-mode, in Emacs 24.

**Comment by jlr** [comment]
Bug report appreciated. Will go ahead and take a look and get back to you. Thanks.

**Comment by jlr** [comment]
OK so I see the same problem, and it's definitely rainbow-delimiters. When the mode gets activated it inherits from the syntax-table of the current buffer major-mode so that it can handle comments, strings, and so forth correctly for any language. I haven't accounted for something in javascript's syntax-table when counting delims (you need to ignore delims in comments, in strings, etc. when determining how deep in you are). The depth count is getting skewed.

I'll get this fixed but it may take some time before I can get to it. This will be the first thing I do next time I sit down to work on the mode.

Thanks for the heads up.

**Comment by purcell** [comment]
Cool. I figured it'd be something related to the syntax table. Thanks for the useful lib.
-Steve

**Comment by jlr** [comment]
Quick update: 

Haven't fixed the bug yet but the problem is clear now. The function 'rainbow-delimiters-depth', which returns the current depth at point, works by going to (beginning-of-defun) followed by doing a (parse-partial-sexp) which determines the nesting depth starting at beginning-of-defun, counting until we reach the desired location.

Because it's used by jit-lock, 'rainbow-delimiters-depth' has to work at any point in the buffer.

In js2-mode, beginning-of-defun works properly for JavaScript - meaning in your example, if inside one of the inner "function() { .... }" blocks, it only takes you out to the start of that inner block. This creates a situation where at certain locations, 'rainbow-delimiters-depth' returns a nested depth only counting from the inner "function () { .... }" block rather than the outermost function. When inside one of these inner functions, an incorrect starting depth is used so the highlighting turns out wrong.

The way to fix this is to use 'beginning-of-defun' repeatedly (or another technique) to get all the way outside to depth 0. At that point parse-partial-sexp will return the correct nesting depth for the desired location. Experimenting with this in your file using eval shows that once outside the entire function, at depth 0, using parse-partial-sexp for a point inside an inner "function () { .... }" block does return the depth count we're looking for.

I'll change this in the mode and put out a bugfix release. I just want to get this information in the bug tracker now to ensure it's not forgotten about. Thanks again for reporting it.

**Comment by purcell** [comment]
Fiddly stuff. Thanks for investigating.

**Comment by jlr** [comment]
Hi, I just fixed this. Your sample file looks good now. Let me know if you see any more issues.

**Comment by purcell** [comment]
Cool, thanks! BTW, ELPA-style packages for the latest versions of rainbow-delimiters are automatically built and hosted in Melpa (http://melpa.milkbox.net), so you might like to mention that in your README for the convenience of potential users.
