### ISSUE TITLE
enhancement: global-rainbow-delimiters-inhibit-modes

### ISSUE THREAD

**Issue by snmishra** [jlr/rainbow-delimiters#7]
Sometimes I edit large SPICE files (a few MBs) in emacs. These files do not have many parentheses. So rainbow-delimiters-mode is not very useful for spice-mode. However, it seems rainbow-delimiters-mode still causes a noticeable slow down while moving around in the buffer. If it is a simple change, I want to request a variable containing a list of major modes where rainbow-delimiters-mode is not activated. Alternatively, a jit-mode may make the configuration unnecessary; I imagine it will be harder to implement.

**Comment by jlr** [comment]
Hi, sorry it took a while to get back to you - I had a drive fail in my mirror and stopped using my desktop til I had a new one in.

I'm going to find a big SPICE file and try to see what is happening here. It shouldn't be slowing you down like that. I scroll through large elisp files (albeit not quite that large) without a hiccup. I'll profile it and take a look at what I can do to make it just work with large files and/or SPICE files, because you shouldn't have to be bothered to disable it just for that. It's already written using jit-lock. This ought be fixable.

I'll also look into a way to exclude certain modes from the global mode since that can be useful in any case.

You can always do M-x rainbow-delimiters-mode to disable it in the current buffer. Right now it might take several seconds to unhighlight very large files if there are lots of delims, but it will work. Making the unhighlighting fn faster is easy, I'll take care of that. For now you could just add a mode-hook to spice mode that disables rainbow-delimiters-mode, e.g.

(add-hook 'spice-mode '(lambda () (rainbow-delimiters-mode -1)))

Thanks for letting me know about this slowdown. I want to hammer out all the edge cases and I appreciate you taking the time.

## 

TODO:
- Profile with a very large SPICE file and fix slowdown.
- Provide way of disabling global-rainbow-delimiters-mode for certain modes automatically.
  (is this normally done by deactivating in mode-hooks or by having an inhibit-modes-list for every single global mode?)
- Speed up the disable/unhighlight fn.

**Comment by jlr** [comment]
Can you check if you're still running into speed problems with the new version? I think this should be fixed now. Thanks.

**Comment by snmishra** [comment]
Sorry for being so late with the response. The response is now much improved. I did not encounter any problem in most files I tested.

There is still a minor slow down and interference with jit-lock-mode when I tested with a 3.8 MB SPICE netlist for this test. But that is far from the typical use case and is trivially fixed by the suggestion in your previous comment. Unfortunately I cannot send the file as a test case. I will see if I can generate one using freely available EDA tools when I get some time, in case you still want to investigate further.
